{% set name = "miutil" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 376e631f2f9701d7e314e5bd3d71612dddb02bc5f521a035a3f12b7cdcb0c310

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - cuinfo = miutil.cuinfo:main
    - mbeautify = miutil.mlab.beautify:main

requirements:
  host:
    - python >=3.4
    - pip
    - setuptools_scm >=3.4
    - toml
  run:
    - python >=3.4
    - nibabel
    - numpy
    - matplotlib-base
    - scipy
    - argopt
    - pynvml
    - requests
    - tqdm >=4.42.0
    - setuptools

test:
  requires:
    - pip
    - pytest
    - pytest-cov
    - pytest-timeout
    - pytest-xdist
  source_files:
    - tests
    - setup.cfg
    - pyproject.toml
  imports:
    - miutil
    - miutil.fdio
    - miutil.imio
    - miutil.plot
    - miutil.web
  commands:
    - pip check
    - pytest -k "not (cuinfo or mlab)" -W="ignore:Using or importing the ABCs:DeprecationWarning"

about:
  home: https://github.com/AMYPAD/miutil
  license: Apache-2.0
  license_family: Apache
  license_file: LICENCE.md
  summary: Medical imaging utilities

  description: |
    Basic functionality needed for https://github.com/AMYPAD/amypad and
    https://github.com/NiftyPET/NiftyPET.

extra:
  recipe-maintainers:
    - casperdcl
